version: "3.3"
services:
  docker-registry:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "docker-registry-volume:/var/lib/docker-registry"
    restart: always
    secrets:
      - ssl_crt
      - ssl_key

secrets:
  ssl_crt:
    file: secret.crt
  ssl_key:
    file: secret.key

volumes:
  docker-registry-volume:
