version: "3.3"
services:
  docker-registry:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "docker-registry-volume:/var/lib/docker-registry"
      - "./secret.crt:/etc/docker/ssl_crt"
      - "./secret.key:/etc/docker/ssl_key"
    restart: always

volumes:
  docker-registry-volume:
